version: '3.11'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=i3z#5es$fdqifu#ok2&3+_*ywroz()su3*_sf8ct9xysj_)pt*
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.25
    restart: always
    environment:
        MYSQL_DATABASE: admin
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - .db:/var/lib/mysql
    ports:
        - "33066:3306"